name: first_flight
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.0'

dependencies:
  flutter:
    sdk: flutter 
  shared_preferences:  ^2.2.2
  camera: ^0.10.5
  geolocator: ^10.1.0
  provider: ^6.0.3
  http: ^1.1.0
  image: ^4.1.3
  url_launcher: ^6.2.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  flutter_launcher_icons: ^0.13.0
  flutter_native_splash: ^2.3.5
  share_plus: ^7.2.1
  flutter_cache_manager: ^3.3.1
  path_provider: ^2.1.1
  # rust_builder:
  #   path: rust_builder
  # flutter_rust_bridge: 2.0.0-dev.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  ffigen: 8.0.2
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

flutter_native_splash:
  color: "#071b5d"
  android: true
  ios: true
  windows: true
  web: true

flutter_launcher_icons:
  image_path: "icon/LogoMk2.png" 
  android: true
  ios: true
  remove_alpha_ios: true
