name: CI
on:
  push: {branches: [main]}
  pull_request:

jobs:

  # TODO-TD: test
  # - build
  # - unit
  # - integration

  format:
    name: "Code formatting"

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dart-lang/setup-dart@v1
    - run: dart --version
    - run: dart format --fix .
    - run: git diff --exit-code
