name: CI
on:
  push: {branches: [main]}
  pull_request:

jobs:
  analyze:
    name: "Static analysis"

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dart-lang/setup-dart@v1
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: "3.0.0"
        channel: 'stable'

    - name: Get dependencies
      run: flutter pub get

    - run: flutter pub run test

    # Runs a set of commands using the runners shell
    - name: Start release build
      run: flutter build appbundle

  format:
    name: "Code formatting"

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dart-lang/setup-dart@v1
    - run: dart --version
    - run: dart format --fix .
    - run: git diff --exit-code
